# Generated by Django 5.2.10 on 2026-02-02 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='date',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='reminder_date',
            field=models.DateField(default=datetime.date(2026, 2, 2)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='reminder_time',
            field=models.TimeField(default=datetime.time(5, 37, 41, 77389)),
            preserve_default=False,
        ),
    ]
