# Generated by Django 5.2.10 on 2026-02-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_time_todoitem_created_at_remove_todoitem_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
